
name: Main workflow

on: push

jobs:
  build:
    runs-on: ububtu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down repository
        uses: actions/checkout@v2
      - run: ci/build-app.sh